# Generated by Django 3.2.5 on 2021-08-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_id', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='shoe', max_length=2083),
        ),
    ]
