# Generated by Django 3.2.5 on 2021-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210806_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shoe_name',
            field=models.CharField(default=1, max_length=500),
        ),
    ]
